#! /bin/bash

promptyn () {
    while true; do
        read -p "$1 " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

for target in .*; do
	# skip directories in repo
  if [ ! -f $target ]; then
  	echo "Skipping $target (directory)."
  else
		link_name="$HOME/$target"
		# prompt user to delete existing
  	if [ -e "$link_name" ]; then
  		# print
      ls --color=auto -l "$link_name"
  		# prompt
			if promptyn "Do you wish to delete the file?"; then
				rm "$link_name"
			else
				continue
			fi
    fi
		# create link
  	echo "Creating $link_name"
  	ln -s "$PWD/$target" "$link_name"
  fi
done
